spring.application.name=sistema

spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_presenca
spring.datasource.username=postgres
spring.datasource.password=1509

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
